language: generic
os: linux
dist: bionic
branches:
  only:
    - master
    - /^v[0-9]+$/
before_install:
  - gem install bundler
install:
  - bundle install
before_script:
  - bundle exec hatchet ci:setup
  - heroku update
  - curl https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz | tar xz -C /tmp/
  - git clone https://github.com/heroku/heroku-buildpack-testrunner.git /tmp/testrunner
script:
  - make $HEROKU_TEST_STACK && /tmp/testrunner/bin/run -c . && bundle exec parallel_rspec -n 5 test/spec/
after_script:
  - bundle exec hatchet destroy --all
env:
  global:
    - IS_RUNNING_ON_CI=true
    - SHUNIT_HOME="/tmp/shunit2-2.1.6"
    - HATCHET_RETRIES=3
    - HATCHET_APP_LIMIT=80
    - HEROKU_APP_LIMIT=9999
    - HATCHET_DEPLOY_STRATEGY=git
    - HATCHET_BUILDPACK_BASE="https://github.com/heroku/heroku-buildpack-jvm"
    - HATCHET_APP_PREFIX="htcht-${TRAVIS_JOB_ID}-"
jobs:
  include:
    - name: "cedar-14"
      env: HEROKU_TEST_STACK=cedar-14
    - name: "heroku-16"
      env: HEROKU_TEST_STACK=heroku-16
    - name: "heroku-18"
      env: HEROKU_TEST_STACK=heroku-18
    - name: "Deploy CNB release tarball on GitHub if the current run is a tag"
      stage: deploy
      script: skip
      deploy:
        provider: releases
        edge: true
        name: "Cloud Native Buildpack (CNB) $TRAVIS_TAG"
        release_notes: "Cloud Native Buildpack (CNB) release. Automatically built after $TRAVIS_TAG of heroku/jvm was released."
        token: $GITHUB_OAUTH_TOKEN
        before_deploy: make package
        file:
          - "heroku-jvm-cnb.tgz"
        on:
          tags: true
