language: generic
os: linux
dist: bionic
branches:
  only:
    - master
    - /^v[0-9]+$/
    - .* # Temporarily allow all for testing
before_install:
  - gem install bundler
install:
  - bundle install
before_script:
  - bundle exec hatchet ci:setup
  - heroku update
  - curl https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz | tar xz -C /tmp/
  - git clone https://github.com/heroku/heroku-buildpack-testrunner.git /tmp/testrunner
script:
  - make $HEROKU_TEST_STACK && /tmp/testrunner/bin/run -c . && bundle exec parallel_rspec -n 5 spec/ && make package
after_script:
  - bundle exec hatchet destroy --all
env:
  global:
    - IS_RUNNING_ON_CI=true
    - SHUNIT_HOME="/tmp/shunit2-2.1.6" # OLD, REQUIRED?
    - HATCHET_RETRIES=3
    - HATCHET_APP_LIMIT=80
    - HEROKU_APP_LIMIT=9999
    - HATCHET_DEPLOY_STRATEGY=git
    - HATCHET_BUILDPACK_BASE="https://github.com/heroku/heroku-buildpack-jvm"
    - HATCHET_APP_PREFIX="htcht-${TRAVIS_JOB_ID}-"
jobs:
  include:
    - env: HEROKU_TEST_STACK=cedar-14
      if: branch = master OR tag IS present
    - env: HEROKU_TEST_STACK=heroku-16
      if: branch = master OR tag IS present
    - env: HEROKU_TEST_STACK=heroku-18
      if: branch = master OR tag IS present
    - env: HEROKU_TEST_STACK=cedar-14 JDK_BASE_URL="- https://lang-jvm.s3.amazonaws.com/jdk/cedar-14" # TODO: Replace with staging bucket
      if: branch != master AND tag IS blank
    - env: HEROKU_TEST_STACK=heroku-16 JDK_BASE_URL="- https://lang-jvm.s3.amazonaws.com/jdk/heroku-16" # TODO: Replace with staging bucket
      if: branch != master AND tag IS blank
    - env: HEROKU_TEST_STACK=heroku-18 JDK_BASE_URL="- https://lang-jvm.s3.amazonaws.com/jdk/heroku-18" # TODO: Replace with staging bucket
      if: branch != master AND tag IS blank

# Cloud Native Buildpack (CNB) Releases
deploy:
  provider: releases
  token: $GITHUB_OAUTH_TOKEN
  file:
    - "heroku-jvm-cnb.tgz"
  skip_cleanup: true
  on:
    tags: true
    condition: $HEROKU_TEST_STACK = heroku-18
